//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TagliatoreWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Platillos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Platillos()
        {
            this.DetalleOrdenes = new HashSet<DetalleOrdenes>();
        }
    
        public int id_platillo { get; set; }
        public string nombre { get; set; }
        public string ingredientes { get; set; }
        public decimal precio { get; set; }
        public string imagen_url { get; set; }
        public Nullable<System.DateTime> fecha_creacion { get; set; }
        public Nullable<System.DateTime> fecha_actualizacion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleOrdenes> DetalleOrdenes { get; set; }
    }
}
